POST http://localhost:5000/
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5jb20iLCJwYXNzd29yZCI6IkphbmVAMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE5Nzg5NzU1LCJleHAiOjE2MTk3OTY5NTV9.I0GD2PBfU74bTXyCyqq0PX6Z6P--wUymTEqA7fqkFCw

{
 "fullName": "John Doe",
 "major": "Computer Science"
}

###
GET http://localhost:5000/
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5jb20iLCJwYXNzd29yZCI6IkphbmVAMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE5Nzg5NzU1LCJleHAiOjE2MTk3OTY5NTV9.I0GD2PBfU74bTXyCyqq0PX6Z6P--wUymTEqA7fqkFCw

###

GET http://localhost:5000/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5jb20iLCJwYXNzd29yZCI6IkphbmVAMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE5Nzg5NzU1LCJleHAiOjE2MTk3OTY5NTV9.I0GD2PBfU74bTXyCyqq0PX6Z6P--wUymTEqA7fqkFCw

###

PUT http://localhost:5000/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5jb20iLCJwYXNzd29yZCI6IkphbmVAMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE5Nzg2OTY3LCJleHAiOjE2MTk3OTQxNjd9.pwln5MYdDFBcUthlPK8dROjU8AmJ04FZ6RVfD3ZcahA

{
 "fullName": "John Park",
 "major": "Math"
}

###

DELETE  http://localhost:5000/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAbWFpbC5jb20iLCJwYXNzd29yZCI6IkphbmVAMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE5Nzg2OTY3LCJleHAiOjE2MTk3OTQxNjd9.pwln5MYdDFBcUthlPK8dROjU8AmJ04FZ6RVfD3ZcahA